####################################
##
##     Project Euler: Problem 12
##
##      Jason Sutter
##      Jasonsutter87@gmail.com
##
##      Answer:    76,576,500
##
###################################
#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
#1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:

# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.

#What is the value of the first triangle number to have over five hundred divisors?

#The sequence of triangle numbers

require "prime"

count = 1
while count < 1000000000
    #Find triangle number
    arr = (1..count)
    $x = arr.inject {|x, y| x + y }
    
    #find Divisions via Tau function.
    y = Prime.prime_division($x)

    #Sum of Divisions
    sum = 1 
    y.each do |x| 
          division = (x[1] + 1)
          sum = sum * division
    end
    
    #if Sum is > 501 print the final number
    if sum >= 501 
       p "The Solution is: " +  $x.to_s
       break
    end
    count += 1
end